#!/bin/bash

set -e

#------------------------------------------------------------------------------
# Copyright (c) 2016, Leonid Bloch
# All rights reserved.
# This code is licensed under standard 3-clause BSD license.
# See file LICENSE supplied with this package for the full license text.
#------------------------------------------------------------------------------

# Install additional packages (add and remove as needed)
sudo pacman -Syu --needed bash-completion rsync xorg-iceauth xorg-sessreg \
    xorg-xcmsdb xorg-xbacklight xorg-xgamma xorg-xhost xorg-xinput \
    xorg-xmodmap xorg-xrandr xorg-xrdb xorg-xrefresh xorg-xset xorg-xsetroot \
    xorg-mkfontdir xorg-mkfontscale xf86-input-libinput gvim htop libx264 \
    the_silver_searcher imagemagick gnuplot hunspell hunspell-en_US ffmpeg \
    unzip mesa-libgl python-opengl sshfs zip python-lxml \
    perl-net-smtp-ssl  perl-authen-sasl perl-mime-tools python-pip \
    python-numpy python-scipy python-sympy python-h5py \
    python-matplotlib python-pillow openmpi

# Vim settings
vm_vim_setup
